### ISSUE TITLE
Setup.py missing Manifest for build

### ISSUE THREAD

**Issue by alericmckearn** [YavorPaunov/deepstreampy#1]
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import deepstreampy
  File "build/bdist.linux-x86_64/egg/deepstreampy/__init__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/deepstreampy/client.py", line 4, in <module>
ImportError: No module named message

I changed setup.py to
setup(name='deepstreampy',
      version='0.1.1',
      **packages=find_packages(),**
      author='Yavor Paunov',
      author_email='contact@yavorpaunov.com',
      description='A deepstream.io client.',
      license='MIT',
      url='https://www.github.com/YavorPaunov/deepstreampy',
     **# packages=['deepstreampy', 'tests', 'features'],**
      long_description=read('README.md'),
      test_suite='tests')

It looks like it is missing a manifest file to make the original code work.

**Comment by charleswhchan** [comment]
I was able to install the latest using the following command without error:
`pip install git+https://github.com/YavorPaunov/deepstreampy`

However, when I use the client, the `deepstreampy.message` submodule is not found
```
Traceback (most recent call last):
  File "/home/linuxmint/work/deepstream/deepstream_client.py", line 1, in <module>
    from deepstreampy.client import Client
  File "/home/linuxmint/work/deepstream-venv/local/lib/python2.7/site-packages/deepstreampy/__init__.py", line 5, in <module>
    from deepstreampy.client import connect
  File "/home/linuxmint/work/deepstream-venv/local/lib/python2.7/site-packages/deepstreampy/client.py", line 4, in <module>
    from deepstreampy.message import connection
ImportError: No module named message
```

**Comment by charleswhchan** [comment]
Since PR#2 has been merged. Can someone try this again and see if this issue can be closed? Thanks.

**Comment by Allan-Nava** [comment]
it works with python 3.7?

**Comment by Allan-Nava** [comment]
https://pypi.org/YavorPaunov/deepstreampy is possible to have in pip package?
